Add thread name ignore regex
nirs/pytest-threadleak pull request #8
Opened 2022-05-18 00:07 UTC by jayvdb

Closes #7

2022-05-18 09:26 UTC, nirs requested changes
Thanks @jayvdb!

Can you add tests covering the new option, and document its usage in README.md?

2022-05-18 09:26 UTC, nirs commented on pytest_threadleak.py
> +                    return
I think the right place to exclude threads is in current_threads().

We can add a exclude argument like:

    def current_threads(exclude=None):

And return frozenset excluding the threads.

2022-05-18 09:26 UTC, nirs commented on pytest_threadleak.py
> +        'threadleak-ignore',
I think using threadleak-exclude is better since we can add in the future threadleak-include, to include only certain threads, and it works like common tools (e.g. tar).

Regarding the option name, shouldn't it be threadleak_exclude? The common convention for ini file options is option_name and command line options is --option-name.

2022-07-01 02:14 UTC, jayvdb commented
Apologies.  I have started a new PR https://github.com/nirs/pytest-threadleak/pull/9 , because my branch "ignore" is used in some of my CI, and renaming the ini option would break that.

2022-07-01 02:14 UTC, closed without merging